### ISSUE TITLE
Binary Packages

### ISSUE THREAD

**Issue by ghost** [cangyu/Sky#1]
Can you produce some binary packages? For example, DEB or AppImage, that could be installed and run under Ubuntu, Linux Mint, etc.

**Comment by cangyu** [comment]
Currently unavailable as the master branch is still under development, I will try this work as soon as I finish the project completely.  
Once I tried to pack the V1.0 using pyinstaller but failed with PyQt, and since then I've spared little effort on this.  
Furthermore, it's convenient to view the generated IGES model file using CATIA, and the generated PLOT3D mesh file will be imported into ANSYS FLUENT for further CFD calculation. So it's not recommended to run these code under *nix OS.
